create table employee as
select EMPLOYEE_ID,FIRST_NAME
from hr.employees;



/*DECLARE 
    V_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_NAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=200;
    DBMS_OUTPUT.PUT_LINE(V_NAME);

END;
*/

/*
DECLARE 
    V_REC HR.EMPLOYEES%ROWTYPE;
BEGIN
    SELECT *INTO V_REC FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=200;
    DBMS_OUTPUT.PUT_LINE(V_REC.EMPLOYEE_ID || '' || V_REC.FIST_NAME);
END;

*/
/*
DECLARE 
TYPE TYPE_NAME IS RECORD(
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20)
);
VARIABLE_NAME VARCHAR(20);
V_REC HR.EMPLOYEES%ROWTYPE;
     V_REC HR.EMPLOYEES%ROWTYPE;
BEGIN
    SELECT *INTO V_REC FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=200;
    DBMS_OUTPUT.PUT_LINE(V_REC.EMPLOYEE_ID || '' || V_REC.FIST_NAME);
END;
*/

/*
DECLARE

    V_REC HR.EMPLOYEES%ROWTYPE;

BEGIN

    SELECT *
    INTO V_REC
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 200;

    DBMS_OUTPUT.PUT_LINE(
        V_REC.EMPLOYEE_ID || ' ' ||
        V_REC.FIRST_NAME || ' ' ||
        V_REC.LAST_NAME
    );

END;
*/
/*
DECLARE
TYPE VARCHAR IS RECORD(
    V_ID     HR.EMPLOYEES.EMPLOYEE_ID 
    V_FNAME  HR.EMPLOYEES.FIRST_NAME 
    V_SALARY HR.EMPLOYEES.SALARY 
);
BEGIN

    SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
    INTO V_ID, V_FNAME, V_SALARY
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 200;

    DBMS_OUTPUT.PUT_LINE('ID = ' || V_ID);
    DBMS_OUTPUT.PUT_LINE('NAME = ' || V_FNAME);
    DBMS_OUTPUT.PUT_LINE('SALARY = ' || V_SALARY);

END;